### ISSUE TITLE
--san parameter is mandatory ?

### ISSUE THREAD

**Issue by DeLoWaN** [loganstellway/self-signed-ssl#14]
Hello,

The `--san` parameter is currently mandatory and makes a prompt if not defined. It should not as this is parameter is optional (it currently fails our automatic scripts).

Thank you !

**Comment by loganstellway** [comment]
Hey there - sorry to hear that.
I should have considered that could be a breaking change. 

For everyone's visibility, [here is the related conversation](https://github.com/loganstellway/self-signed-ssl/commit/3551d48735c01f919ea808d4e4884a95fd1fcb17#commitcomment-45294193) that lead to adding the variable prompt. 

I agree it makes sense to not _(always)_ prompt for the option since it is optional. 
To attend to both needs, one idea is to only prompt for the `SAN` values when both the `--common-name` (primary domain) and the `--san` (subject alternative names) arguments are not provided. 

Feedback?

**Comment by DeLoWaN** [comment]
Sounds good to me ! Thank you.
